import { IProjectContent } from "./index.interface"

export const trackOptions:string[] = ["fdt", "qa", "bdt"];

export const projectOptions: IProjectContent[]= [
    {
      "id": "qeats",
      "name": "QEats",
      "languages": "Java, REST, Spring Boot, MongoDB, Redis, JUnit, Mockito, MVCS, Spring Data, Multithreading",
      "demoLink": "https://github.com/apoorvb12/qeats",
      "timeline": "2012-01-01",
      "intro": "QEats is a food ordering app that allows users to browse and order their favourite dishes from nearby restaurants.",
      "description": "",
      "track": "bdt"
    },
    {
      "id": "qmoney",
      "name": "QMoney",
      "languages": "Java, Jackson, Factory Design Pattern, JUnit, Mockito, REST",
      "demoLink": "https://github.com/apoorvb12/qeats",
      "timeline": "2012-01-01",
      "intro": "QMoney is a visual stock portfolio analyzer. It helps portfolio managers make trade recommendations for their clients.",
       "description":"",
       "track": "bdt"
    },
    {
      "id": "xform",
      "name": "XForm",
      "languages": "Java, Spring Boot, MongoDB, Spring Data",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "bdt"
    },
    {
      "id": "xcommerce",
      "name": "XCommerce",
      "languages": "Java, Jackson, JUnit",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "bdt",
    },
    {
      "id": "xflix",
      "name": "XFlix",
      "languages": "React.js, JSX, Figma, Mock API server, Single Page Application, NPM, Netlify, JSX",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "fdt",
    },
    {
      "id": "qkart",
      "name": "Qkart",
      "languages": "React.js, JSX, Single Page Application, NPM, Reusable Components, Debouncing, Conditional Rendering, React Router, LocalStorage API, Password-based Authentication, Bearer Token, React Refs, Ant Design, Netlify, Heroku",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "fdt",
    },
    {
      "id": "xboard",
      "name": "XBoard",
      "languages": "JavaScript, JQuery, HTML5, CSS3, Bootstrap, Figma, DOM Manipulation, Netlify",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "fdt",
    },
    {
      "id": "qtrip",
      "name": "Qtrip",
      "languages": "JavaScript, JQuery, HTML5, CSS3, Bootstrap, Wireframe, Dynamic webpage, DOM Manipulation, Netlify, Heroku",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "fdt",
    },
    {
      "id": "qcalc",
      "name": "QCalc",
      "languages": "Java, OOPs, IDE, Debugger, JUnit, Exception Handling",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "qa",
    },
    {
      "id": "qkart",
      "name": "QKart",
      "languages": "Selenium, Web Driver, TestNG, Apache POI, Cucumber, Page Object Model, Grid, Web Driver Manager, XPath, Extent Report, Apache Log4J",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "qa",
    },
]