import { IProjectContent } from "./index.interface"

export const trackOptions:string[] = ["fdt", "qa", "bdt"];

export const projectOptions: IProjectContent[]= [
    {
      "id": "qeats",
      "name": "QEats",
      "languages": "Java, REST, Spring Boot, MongoDB, Redis, JUnit, Mockito, MVCS, Spring Data, Multithreading",
      "demoLink": "https://github.com/apoorvb12/qeats",
      "timeline": "2012-01-01",
      "intro": "QEats is a food ordering app that allows users to browse and order their favourite dishes from nearby restaurants.",
      "description": "",
      "track": "bdt"
    },
    {
      "id": "qmoney",
      "name": "QMoney",
      "languages": "Java, Jackson, Factory Design Pattern, JUnit, Mockito, REST",
      "demoLink": "https://github.com/apoorvb12/qeats",
      "timeline": "2012-01-01",
      "intro": "QMoney is a visual stock portfolio analyzer. It helps portfolio managers make trade recommendations for their clients.",
       "description":"",
       "track": "bdt"
    },
    {
      "id": "xform",
      "name": "XForm",
      "languages": "Java, Spring Boot, MongoDB, Spring Data",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "bdt"
    },
    {
      "id": "xcommerce",
      "name": "XCommerce",
      "languages": "Java, Jackson, JUnit",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "bdt",
    },
    {
      "id": "xflix",
      "name": "XFlix",
      "languages": "React.js, JSX, Figma, Mock API server, Single Page Application, NPM, Netlify, JSX",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "fdt",
    },
    {
      "id": "qkart",
      "name": "Qkart",
      "languages": "React.js, JSX, Single Page Application, NPM, Reusable Components, Debouncing, Conditional Rendering, React Router, LocalStorage API, Password-based Authentication, Bearer Token, React Refs, Ant Design, Netlify, Heroku",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "fdt",
    },
    {
      "id": "xboard",
      "name": "XBoard",
      "languages": "JavaScript, JQuery, HTML5, CSS3, Bootstrap, Figma, DOM Manipulation, Netlify",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "fdt",
    },
    {
      "id": "qtrip",
      "name": "Qtrip",
      "languages": "JavaScript, HTML5, CSS3, Bootstrap, Wireframe, Dynamic webpage, DOM Manipulation, Netlify, Render",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
      "description":"<ul><li>A travel website made using HTML, CSS, Bootstrap, and JavaScript that can be used to browse different cities, and adventures and make reservations.</li><li>Improved UI/UX with multi-select filters, forms, image carousels, and conditional rendering of page elements.</li><li>Utilized localStorage to persist user preference at client-side and facilitated reservation form submission using fetch API.</li><li>Deployed the website using Netlify for Frontend and Render for Backend.</li></ul>",
       "track": "fdt",
    },
    {
      "id": "qcalc",
      "name": "QCalc",
      "languages": "Java, OOPs, IDE, Debugger, JUnit, Exception Handling",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
      "description":"",
       "track": "qa",
    },
    {
      "id": "qkart",
      "name": "QKart",
      "languages": "Selenium, Web Driver, TestNG, Apache POI, Cucumber, Page Object Model, Grid, Web Driver Manager, XPath, Extent Report, Apache Log4J",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
       "description":"",
       "track": "qa",
    },
    {
      "id": "qtripstatic",
      "name": "Qtrip-Static",
      "languages": "HTML, CSS, Developer Tools, Bootstrap, Responsive Design, Deployment using Netlify, VS Code Live Server",
      "demoLink": "",
      "timeline": "2012-01-01",
      "intro": "",
      "description":"<ul><li>Created 3 different web pages from wireframe layout using HTML and CSS.</li><li>Utilized Bootstrap extensively for responsive design, and creating components.</li><li>Deployed the website using Netlify.</li></ul>",
      "track": "fdt",
    },
]